# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default:
            url: '%env(ELASTICSEARCH_URL)%'
    indexes:
        freelance:
            finder: true
            persistence:
                driver: orm
                model: App\Entity\FreelanceConso
                provider: ~
            properties:
                firstName: ~
                lastName: ~
                jobTitle: ~
                linkedInUrl: ~
                fullName: ~